In [6]:
import pandas as pd

In [7]:
rent_path = "../data/raw/ons_private_rents_monthly_june_2026.xlsx"

excel_file = pd.ExcelFile(rent_path)

excel_file.sheet_names

['Cover sheet', 'Contents', 'Notes', 'Table 1']

In [14]:
rent_df = pd.read_excel(
    rent_path,
    sheet_name='Table 1',
    skiprows = 2
)

rent_df.head()

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [15]:
rent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48909 entries, 0 to 48908
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Time period                      48909 non-null  datetime64[us]
 1   Area code                        48909 non-null  str
 2   Area name                        48909 non-null  str
 3   Region or country name           48909 non-null  str
 4   Index                            48909 non-null  object
 5   Monthly change                   48909 non-null  object
 6   Annual change                    48909 non-null  object
 7   Rental price                     48909 non-null  object
 8   Index one bed                    48909 non-null  object
 9   Monthly change one bed           48909 non-null  object
 10  Annual change one bed            48909 non-null  object
 11  Rental price one bed             48909 non-null  object
 12  Index two bed                    48909 non-null  object
 13  Monthly change two bed           48909 non-null  object
 14  Annual change two bed            48909 non-null  object
 15  Rental price two bed             48909 non-null  object
 16  Index three bed                  48909 non-null  object
 17  Monthly change three bed         48909 non-null  object
 18  Annual change three bed          48909 non-null  object
 19  Rental price three bed           48909 non-null  object
 20  Index four or more bed           48909 non-null  object
 21  Monthly change four or more bed  48909 non-null  object
 22  Annual change four or more bed   48909 non-null  object
 23  Rental price four or more bed    48909 non-null  object
 24  Index detached                   48909 non-null  object
 25  Monthly change detached          48909 non-null  object
 26  Annual change detached           48909 non-null  object
 27  Rental price detached            48909 non-null  object
 28  Index semidetached               48909 non-null  object
 29  Monthly change semidetached      48909 non-null  object
 30  Annual change semidetached       48909 non-null  object
 31  Rental price semidetached        48909 non-null  object
 32  Index terraced                   48909 non-null  object
 33  Monthly change terraced          48909 non-null  object
 34  Annual change terraced           48909 non-null  object
 35  Rental price terraced            48909 non-null  object
 36  Index flat maisonette            48909 non-null  object
 37  Monthly change flat maisonette   48909 non-null  object
 38  Annual change flat maisonette    48909 non-null  object
 39  Rental price flat maisonette     48909 non-null  object
dtypes: datetime64[us](1), object(36), str(3)
memory usage: 16.4+ MB

In [17]:
rent_df.columns

Index(['Time period', 'Area code', 'Area name', 'Region or country name',
       'Index', 'Monthly change', 'Annual change', 'Rental price',
       'Index one bed', 'Monthly change one bed', 'Annual change one bed',
       'Rental price one bed', 'Index two bed', 'Monthly change two bed',
       'Annual change two bed', 'Rental price two bed', 'Index three bed',
       'Monthly change three bed', 'Annual change three bed',
       'Rental price three bed', 'Index four or more bed',
       'Monthly change four or more bed', 'Annual change four or more bed',
       'Rental price four or more bed', 'Index detached',
       'Monthly change detached', 'Annual change detached',
       'Rental price detached', 'Index semidetached',
       'Monthly change semidetached', 'Annual change semidetached',
       'Rental price semidetached', 'Index terraced',
       'Monthly change terraced', 'Annual change terraced',
       'Rental price terraced', 'Index flat maisonette',
       'Monthly change flat maisonette', 'Annual change flat maisonette',
       'Rental price flat maisonette'],
      dtype='str')

In [19]:
rent_df.to_csv(
    "../data/processed/private_rents_clean_initial.csv",
    index=False
)

In [20]:
import pandas as pd

check_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

check_df.head()

/var/folders/lr/w4xj03s57999l3j70hd_bdlw0000gn/T/ipykernel_57097/1604025186.py:3: DtypeWarning: Columns (0: Index, 1: Rental price, 2: Index one bed, 3: Rental price one bed, 4: Index two bed, 5: Rental price two bed, 6: Index three bed, 7: Rental price three bed, 8: Index four or more bed, 9: Rental price four or more bed, 10: Index detached, 11: Rental price detached, 12: Index semidetached, 13: Rental price semidetached, 14: Index terraced, 15: Rental price terraced, 16: Index flat maisonette, 17: Rental price flat maisonette) have mixed types. Specify dtype option on import or set low_memory=False.
  check_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [22]:
check_df.shape

(48909, 40)