<h2>Rent prices data</h2>

In [6]:
# Import pandas
import pandas as pd

In [8]:
# create pandas df from raw data
rent_path = "../data/raw/ons_private_rents_monthly_june_2026.xlsx"

excel_file = pd.ExcelFile(rent_path)

excel_file.sheet_names

['Cover sheet', 'Contents', 'Notes', 'Table 1']

In [9]:
# select the correct table and rows
rent_df = pd.read_excel(
    rent_path,
    sheet_name='Table 1',
    skiprows = 2
)

rent_df.head()

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [15]:
rent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48909 entries, 0 to 48908
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Time period                      48909 non-null  datetime64[us]
 1   Area code                        48909 non-null  str
 2   Area name                        48909 non-null  str
 3   Region or country name           48909 non-null  str
 4   Index                            48909 non-null  object
 5   Monthly change                   48909 non-null  object
 6   Annual change                    48909 non-null  object
 7   Rental price                     48909 non-null  object
 8   Index one bed                    48909 non-null  object
 9   Monthly change one bed           48909 non-null  object
 10  Annual change one bed            48909 non-null  object
 11  Rental price one bed             48909 non-null  object
 12  Index two bed                    48909 non-null  object
 13  Monthly change two bed           48909 non-null  object
 14  Annual change two bed            48909 non-null  object
 15  Rental price two bed             48909 non-null  object
 16  Index three bed                  48909 non-null  object
 17  Monthly change three bed         48909 non-null  object
 18  Annual change three bed          48909 non-null  object
 19  Rental price three bed           48909 non-null  object
 20  Index four or more bed           48909 non-null  object
 21  Monthly change four or more bed  48909 non-null  object
 22  Annual change four or more bed   48909 non-null  object
 23  Rental price four or more bed    48909 non-null  object
 24  Index detached                   48909 non-null  object
 25  Monthly change detached          48909 non-null  object
 26  Annual change detached           48909 non-null  object
 27  Rental price detached            48909 non-null  object
 28  Index semidetached               48909 non-null  object
 29  Monthly change semidetached      48909 non-null  object
 30  Annual change semidetached       48909 non-null  object
 31  Rental price semidetached        48909 non-null  object
 32  Index terraced                   48909 non-null  object
 33  Monthly change terraced          48909 non-null  object
 34  Annual change terraced           48909 non-null  object
 35  Rental price terraced            48909 non-null  object
 36  Index flat maisonette            48909 non-null  object
 37  Monthly change flat maisonette   48909 non-null  object
 38  Annual change flat maisonette    48909 non-null  object
 39  Rental price flat maisonette     48909 non-null  object
dtypes: datetime64[us](1), object(36), str(3)
memory usage: 16.4+ MB

In [17]:
rent_df.columns

Index(['Time period', 'Area code', 'Area name', 'Region or country name',
       'Index', 'Monthly change', 'Annual change', 'Rental price',
       'Index one bed', 'Monthly change one bed', 'Annual change one bed',
       'Rental price one bed', 'Index two bed', 'Monthly change two bed',
       'Annual change two bed', 'Rental price two bed', 'Index three bed',
       'Monthly change three bed', 'Annual change three bed',
       'Rental price three bed', 'Index four or more bed',
       'Monthly change four or more bed', 'Annual change four or more bed',
       'Rental price four or more bed', 'Index detached',
       'Monthly change detached', 'Annual change detached',
       'Rental price detached', 'Index semidetached',
       'Monthly change semidetached', 'Annual change semidetached',
       'Rental price semidetached', 'Index terraced',
       'Monthly change terraced', 'Annual change terraced',
       'Rental price terraced', 'Index flat maisonette',
       'Monthly change flat maisonette', 'Annual change flat maisonette',
       'Rental price flat maisonette'],
      dtype='str')

In [19]:
rent_df.to_csv(
    "../data/processed/private_rents_clean_initial.csv",
    index=False
)

In [20]:
import pandas as pd

check_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

check_df.head()

/var/folders/lr/w4xj03s57999l3j70hd_bdlw0000gn/T/ipykernel_57097/1604025186.py:3: DtypeWarning: Columns (0: Index, 1: Rental price, 2: Index one bed, 3: Rental price one bed, 4: Index two bed, 5: Rental price two bed, 6: Index three bed, 7: Rental price three bed, 8: Index four or more bed, 9: Rental price four or more bed, 10: Index detached, 11: Rental price detached, 12: Index semidetached, 13: Rental price semidetached, 14: Index terraced, 15: Rental price terraced, 16: Index flat maisonette, 17: Rental price flat maisonette) have mixed types. Specify dtype option on import or set low_memory=False.
  check_df = pd.read_csv("../data/processed/private_rents_clean_initial.csv")

,Time period,Area code,Area name,Region or country name,Index,Monthly change,Annual change,Rental price,Index one bed,Monthly change one bed,...,Annual change semidetached,Rental price semidetached,Index terraced,Monthly change terraced,Annual change terraced,Rental price terraced,Index flat maisonette,Monthly change flat maisonette,Annual change flat maisonette,Rental price flat maisonette
0,2015-01-01,K02000001,United Kingdom,[z],81.258259,[x],[x],910,82.339979,[x],...,[x],897,80.345118,[x],[x],893,83.26757,[x],[x],904
1,2015-02-01,K02000001,United Kingdom,[z],81.413747,0.191351,[x],912,82.53953,0.24235,...,[x],899,80.478716,0.166281,[x],894,83.457123,0.227644,[x],906
2,2015-03-01,K02000001,United Kingdom,[z],81.663685,0.306997,[x],915,82.781781,0.293496,...,[x],901,80.72993,0.312149,[x],897,83.73479,0.332706,[x],909
3,2015-04-01,K02000001,United Kingdom,[z],81.990506,0.400204,[x],918,83.232795,0.544823,...,[x],904,80.995081,0.328442,[x],900,84.194112,0.548543,[x],914
4,2015-05-01,K02000001,United Kingdom,[z],82.343646,0.430708,[x],922,83.597644,0.438349,...,[x],908,81.33684,0.421951,[x],904,84.638073,0.527307,[x],918

In [22]:
check_df.shape

(48909, 40)

<h2>Earnings and employment data collection</h2>

In [10]:
# data collection

wage_path = "../data/raw/ons_pay_rti_seasonally_adjusted_june_2026.xlsx"

wage_excel = pd.ExcelFile(wage_path)

wage_excel.sheet_names

['Index',
 '1. Payrolled employees (UK)',
 '2. Median pay (UK)',
 '3. Mean pay (UK)',
 '4. Aggregate pay (UK)',
 '5. Pay distribution (UK)',
 '6. Employee flows (UK)',
 '7. Employees (NUTS1)',
 '8. Median pay (NUTS1)',
 '9. Mean pay (NUTS1)',
 '10. Aggregate pay (NUTS1)',
 '11. Employees (NUTS2)',
 '12. Median pay (NUTS2)',
 '13. Mean pay (NUTS2)',
 '14. Aggregate pay (NUTS2)',
 '15. Employees (NUTS3)',
 '16. Median pay (NUTS3)',
 '17. Mean pay (NUTS3)',
 '18. Aggregate pay (NUTS3)',
 '19. Employees (LA)',
 '20. Median pay (LA)',
 '21. Mean pay (LA)',
 '22. Aggregate pay (LA)',
 '23. Employees (Industry)',
 '24. Median pay (Industry)',
 '25. Mean pay (Industry)',
 '26. Aggregate pay (Industry)',
 '27. Median of pay growth (UK)',
 '28. Employees (Age)',
 '29. Median pay (Age)',
 '30. Mean pay (Age)',
 '31. Aggregate pay (Age)',
 '32. Employees (NUTS1Age)',
 '33. Median pay (NUTS1Age)',
 '34. Mean pay (NUTS1Age)',
 '35. Aggregate pay (NUTS1Age)',
 '36. Employees (NUTS1Sector)',
 '37. Median pay (NUTS1Sector)',
 '38. Mean pay (NUTS1Sector)',
 '39. Aggregate pay (NUTS1Sector)']

In [14]:
# select the correct table and rows
wage_df = pd.read_excel(
    wage_path,
    sheet_name='8. Median pay (NUTS1)',
    skiprows=6
)

wage_df.head()

,Date,North East,North West,Yorkshire and The Humber,East Midlands,West Midlands,East,London,South East,South West,Wales,Scotland,Northern Ireland,UK
0,July 2014,1524,1512,1493,1510,1515,1638,1928,1715,1493,1498,1647,1488,1598
1,August 2014,1527,1513,1496,1511,1521,1645,1932,1718,1497,1497,1650,1486,1601
2,September 2014,1528,1516,1497,1513,1521,1647,1932,1721,1500,1501,1649,1493,1604
3,October 2014,1533,1514,1502,1515,1518,1640,1934,1722,1503,1498,1649,1487,1601
4,November 2014,1536,1523,1507,1521,1529,1647,1937,1726,1508,1510,1653,1503,1611

In [15]:
wage_df.to_csv(
    "../data/processed/wages_clean_initial.csv",
    index=False
)

<h2>Inflation data collection</h2>

In [17]:
inflation_path = "../data/raw/ons_cpih_index_june_2026.csv"

inflation_df = pd.read_csv(inflation_path)

inflation_df.head()

/var/folders/lr/w4xj03s57999l3j70hd_bdlw0000gn/T/ipykernel_58787/1441711918.py:3: DtypeWarning: Columns (0: CPI wts: Non-energy industrial goods GOODS, 1: CPI wts: Durables GOODS, 2: CPI wts: Semi-durables GOODS, 3: CPI wts: Non-durables GOODS, 4: CPI wts: Non-seasonal food GOODS, 5: CPI wts: Food, alcoholic beverages & tobacco GOODS, 6: CPI wts: Processed food & non-alcoholic beverages GOODS, 7: CPI wts: Unprocessed food GOODS, 8: CPI wts: Seasonal food GOODS, 9: CPI wts: Industrial goods GOODS, 10: CPI wts: Energy GOODS, 11: CPI wts: Electricity, gas & misc. energy GOODS, 12: CPI wts: CPI excluding tobacco SPECIAL AGGREGATES, 13: CPI wts: Clothing & footwear goods GOODS, 14: CPI wts: Housing goods GOODS, 15: CPI wts: Household goods GOODS, 16: CPI wts: Water supply; materials for maintenance & repair GOODS, 17: CPI wts: Medical goods GOODS, 18: CPI wts: Vehicles, spare parts & accessories GOODS, 19: CPI wts: Recreational goods GOODS, 20: CPI wts: Audio-visual goods GOODS, 21: CPI wts: Other recreational goods GOODS, 22: CPI wts: Miscellaneous goods GOODS, 23: CPI wts: Housing services SERVICES, 24: CPI wts: Primary housing services SERVICES, 25: CPI wts: Other housing services SERVICES, 26: CPI wts: Travel & transport services SERVICES, 27: CPI wts: Services for personal transport equipment SERVICES, 28: CPI wts: Recreational & personal services SERVICES, 29: CPI wts: Package holidays & accommodation SERVICES, 30: CPI wts: Other recreational & personal services SERVICES, 31: CPI wts: Non-catering recreational & personal services SERVICES, 32: CPI wts: Miscellaneous services SERVICES, 33: CPI wts: Miscellaneous & other services SERVICES, 34: CPI wts: Medical services (dec 1999=100) SERVICES, 35: CPI wts: Liquid fuels, vehicle fuels & lubricants GOODS, 36: CPI wts: CPI excluding energy SPECIAL AGGREGATES, 37: CPI wts: CPI excluding energy, food, alcohol & tobacco SPECIAL AGGREGATES, 38: CPI wts: CPI excluding energy & unprocessed food SPECIAL AGGREGATES, 39: CPI wts: CPI excluding seasonal food SPECIAL AGGREGATES, 40: CPI wts: CPI excluding energy & seasonal food SPECIAL AGGREGATES, 41: CPI wts: CPI excluding alcohol & tobacco SPECIAL AGGREGATES, 42: CPI wts: CPI ex. liquid fuels, vehicle fuels & lubricants SPECIAL AGGREGATES, 43: CPI wts: CPI ex. housing, water, elec., gas & other fuels SPECIAL AGGREGATES, 44: CPI wts: CPI ex. education, health & social protection SPECIAL AGGREGATES, 45: CPI wts: Energy, food, alcohol and tobacco SPECIAL AGGREGATES, 46: CPI wts: Energy and unprocessed food SPECIAL AGGREGATES, 47: CPI wts: Energy and seasonal food SPECIAL AGGREGATES, 48: CPI wts: Education, health and social protection SPECIAL AGGREGATES, 49: Internal purchasing power of the pound (based on RPI): 1977=100, 50: Internal purchasing power of the pound (based on RPI): 1978=100, 51: Internal purchasing power of the pound (based on RPI): 1979=100, 52: Internal purchasing power of the pound (based on RPI): 1980=100, 53: Internal purchasing power of the pound (based on RPI): 1981=100, 54: Internal purchasing power of the pound (based on RPI): 1982=100, 55: Internal purchasing power of the pound (based on RPI): 1983=100, 56: Internal purchasing power of the pound (based on RPI): 1984=100, 57: Internal purchasing power of the pound (based on RPI): 1985=100, 58: Internal purchasing power of the pound (based on RPI): 1986=100, 59: Internal purchasing power of the pound (based on RPI): 1987=100, 60: Internal purchasing power of the pound (based on RPI): 1988=100, 61: Internal purchasing power of the pound (based on RPI): 1989=100, 62: Internal purchasing power of the pound (based on RPI): 1990=100, 63: Internal purchasing power of the pound (based on RPI): 1991=100, 64: Internal purchasing power of the pound (based on RPI): 2004=100, 65: RPI:Percentage change over 12 months - Milk fresh, 66: RPI:Percentage change over 12 months - Milk products, 67: RPI:Percentage change over 12 months - Tea, 68: RPI:Percentage change over 12 months - Coffee and other hot drinks, 69: RPI:Weights (parts per 1000) One-person pensioner - Take-aways and snacks, 70: RPI:Weights (parts per 1000) One-person pensioner - Beer on sales, 71: RPI:Weights (parts per 1000) One-person pensioner - Beer off sales, 72: RPI:Weights (parts per 1000) One-person pensioner - Wines & spirits on sales, 73: RPI:Weights (parts per 1000) One-person pensioner - Wines & spirits off sales, 74: RPI:Weights (parts per 1000) One-person pensioner - Cigarettes, 75: RPI:Weights (parts per 1000) One-person pensioner - Other Tobacco, 76: RPI:Weights (parts per 1000) - Food and Catering, 77: RPI:Weights (parts per 1000) - Alcohol and Tobacco, 78: RPI:Weights (parts per 1000) - Housing and Household Expenditure, 79: RPI:Weights (parts per 1000) - Personal Expenditure, 80: RPI:Weights (parts per 1000) - Travel and Leisure, 81: RPI:Weights (parts per 1000) - Consumer Durables, 82: RPI:Weights (parts per 1000) One-person pensioner - Foreign holidays, 83: RPI:Weights (parts per 1000) One-person pensioner - Coal and solid fuels, 84: RPI:Weights (parts per 1000) One-person pensioner - Electricity, 85: RPI:Weights (parts per 1000) One-person pensioner - Gas, 86: RPI:Weights (parts per 1000) One-person pensioner - Oil and other fuels, 87: RPI:Weights (parts per 1000) One-person pensioner - Furniture, 88: RPI:Weights (parts per 1000) One-person pensioner - Furnishings, 89: RPI:Weights (parts per 1000) One-person pensioner - Electrical appliances, 90: RPI:Weights (parts per 1000) One-person pensioner - Other household equipment, 91: RPI:Weights (parts per 1000) One-person pensioner - Household consumables, 92: RPI:Weights (parts per 1000) One-person pensioner - Pet care, 93: RPI:Weights (parts per 1000) One-person pensioner - Postage, 94: RPI:Weights (parts per 1000) One-person pensioner - Telephones, telemessages, et, 95: RPI:Weights (parts per 1000) One-person pensioner - Domestic services, 96: RPI:Weights (parts per 1000) One-person pensioner - Fees and subscriptions, 97: RPI:Weights (parts per 1000) One-person pensioner - Men's outerwear, 98: RPI:Weights (parts per 1000) One-person pensioner - Women's outerwear, 99: RPI:Weights (parts per 1000) One-person pensioner - Children's outerwear, 100: RPI:Weights (parts per 1000) One-person pensioner - Other clothing, 101: RPI:Weights (parts per 1000) One-person pensioner - Footwear, 102: RPI:Weights (parts per 1000) One-person pensioner - Personal articles, 103: RPI:Weights (parts per 1000) One-person pensioner - Chemists goods, 104: RPI:Weights (parts per 1000) One-person pensioner - Personal services, 105: RPI:Weights (parts per 1000) One-person pensioner - Purchase of motor vehicles, 106: RPI:Weights (parts per 1000) One-person pensioner - Maintenance of motor vehicle, 107: RPI:Weights (parts per 1000) One-person pensioner - Petrol and oil, 108: RPI:Weights (parts per 1000) One-person pensioner - Vehicles tax and insurance, 109: RPI:Weights (parts per 1000) One-person pensioner - Rail fares, 110: RPI:Weights (parts per 1000) One-person pensioner - Bus and coach fares, 111: RPI:Weights (parts per 1000) One-person pensioner - Other travel costs, 112: RPI:Weights (parts per 1000) One-person pensioner - Audio-visual equipment, 113: RPI:Weights (parts per 1000) One-person pensioner - Records and tapes, 114: RPI:Weights (parts per 1000) One-person pensioner - Toys, photographic & sports, 115: RPI:Weights (parts per 1000) One-person pensioner - Books and newspapers, 116: RPI:Weights (parts per 1000) One-person pensioner - Gardening products, 117: RPI:Weights (parts per 1000) One-person pensioner - Television licences and rent, 118: RPI:Weights (parts per 1000) One-person pensioner - Entertainment & other recrea, 119: RPI:Weights (parts per 1000) Two person pensioner - Foreign holidays, 120: RPI:Weights (parts per 1000) - Foreign holidays, 121: RPI:Weights (parts per 1000) One-person pensioner - Food, 122: RPI:Weights (parts per 1000) One-person pensioner - Catering, 123: RPI:Weights (parts per 1000) One-person pensioner - Alcoholic drink, 124: RPI:Weights (parts per 1000) One-person pensioner - Tobacco, 125: Internal purchasing power of the pound (based on RPI): 1993=100, 126: RPI:Weights (parts per 1000) One-person pensioner - Fuel and light, 127: RPI:Weights (parts per 1000) One-person pensioner - Household goods, 128: RPI:Weights (parts per 1000) One-person pensioner - Household services, 129: RPI:Weights (parts per 1000) One-person pensioner - Clothing and footwear, 130: RPI:Weights (parts per 1000) One-person pensioner - Personal goods and services, 131: RPI:Weights (parts per 1000) One-person pensioner - Motoring expenditure, 132: RPI:Weights (parts per 1000) One-person pensioner - Fares and other travel costs, 133: RPI:Weights (parts per 1000) One-person pensioner - Leisure goods, 134: RPI:Weights (parts per 1000) One-person pensioner - Leisure services, 135: RPI:Weights (parts per 1000) Two-person pensioner - Bread, 136: RPI:Weights (parts per 1000) Two-person pensioner - Cereals, 137: RPI:Weights (parts per 1000) Two-person pensioner - Biscuits and cakes, 138: RPI:Weights (parts per 1000) Two-person pensioner - Beef, 139: RPI:Weights (parts per 1000) Two-person pensioner - Home-killed lamb, 140: RPI:Weights (parts per 1000) Two-person pensioner - imported lamb, 141: RPI:Weights (parts per 1000) Two-person pensioner - Pork, 142: RPI:Weights (parts per 1000) Two-person pensioner - Bacon, 143: RPI:Weights (parts per 1000) Two-person pensioner - Poultry, 144: RPI:Weights (parts per 1000) Two-person pensioner - Other meat, 145: RPI:Weights (parts per 1000) Two-person pensioner - Fresh fish, 146: RPI:Weights (parts per 1000) Two-person pensioner - processed fish, 147: RPI:Weights (parts per 1000) Two-person pensioner - Butter, 148: RPI:Weights (parts per 1000) Two-person pensioner - Oils and fats, 149: RPI:Weights (parts per 1000) Two-person pensioner - Cheese, 150: RPI:Weights (parts per 1000) Two-person pensioner - Eggs, 151: RPI:Weights (parts per 1000) Two-person pensioner - Milk, fresh, 152: RPI:Weights (parts per 1000) Two-person pensioner - Milk products, 153: RPI:Weights (parts per 1000) Two-person pensioner - Tea, 154: RPI:Weights (parts per 1000) Two-person pensioner - Coffee and other hot drinks, 155: RPI:Weights (parts per 1000) Two-person pensioner - Soft drinks, 156: RPI:Weights (parts per 1000) Two-person pensioner - Sugar and preserves, 157: RPI:Weights (parts per 1000) Two-person pensioner - Sweets and chocolates, 158: RPI:Weights (parts per 1000) Two-person pensioner - Unprocessed potatoes, 159: RPI:Weights (parts per 1000) Two-person pensioner - Processed potatoes, 160: RPI:Weights (parts per 1000) Two-person pensioner - Fresh vegetables, 161: RPI:Weights (parts per 1000) Two-person pensioner - Processed vegetables, 162: RPI:Weights (parts per 1000) Two-person pensioner - Fresh fruit, 163: RPI:Weights (parts per 1000) Two-person pensioner - Processed fruit, 164: RPI:Weights (parts per 1000) Two-person pensioner - Other foods, 165: RPI:Weights (parts per 1000) Two-person pensioner - Restaurant meals, 166: RPI:Weights (parts per 1000) Two-person pensioner - Canteen meals, 167: RPI:Weights (parts per 1000) Two-person pensioner - Take-aways and snacks, 168: RPI:Weights (parts per 1000) Two-person pensioner - beer on sales, 169: RPI:Weights (parts per 1000) Two-person pensioner - beer off sales, 170: RPI:Weights (parts per 1000) Two-person pensioner - wines & spirits on sales, 171: RPI:Weights (parts per 1000) Two-person pensioner - wines & spirits off sales, 172: RPI:Weights (parts per 1000) Two-person pensioner - Cigarettes, 173: RPI:Weights (parts per 1000) Two-person pensioner - Other Tobacco, 174: RPI:All items exc mortgage int payments and indirect taxes (RPIY) (Jan 1987=100), 175: RPI:Percentage change over 12 months - All items exc MIPs and indirect taxes, 176: RPI:Percentage change over 12 months - All items excluding food, 177: RPI:Percentage change over 12 months - Food, 178: RPI:Percentage change over 12 months - Bread, 179: RPI:Percentage change over 12 months - Cereals, 180: RPI:Weights (parts per 1000) Two-person pensioner - Coal and solid fuels, 181: RPI:Weights (parts per 1000) Two-person pensioner - Electricity, 182: RPI:Weights (parts per 1000) Two-person pensioner - Gas, 183: RPI:Weights (parts per 1000) Two-person pensioner - Oil and other fuels, 184: RPI:Weights (parts per 1000) Two-person pensioner - Furniture, 185: RPI:Weights (parts per 1000) Two-person pensioner - Furnishings, 186: RPI:Weights (parts per 1000) Two-person pensioner - Electrical appliances, 187: RPI:Weights (parts per 1000) Two-person pensioner - Other household equipment, 188: RPI:Weights (parts per 1000) Two-person pensioner - Household consumables, 189: RPI:Weights (parts per 1000) Two-person pensioner - Pet care, 190: RPI:Weights (parts per 1000) Two-person pensioner - Postage, 191: RPI:Weights (parts per 1000) Two-person pensioner - Telephones, telemessages, et, 192: RPI:Weights (parts per 1000) Two-person pensioner - Domestic services, 193: RPI:Weights (parts per 1000) Two-person pensioner - Fees and subscriptions, 194: RPI:Weights (parts per 1000) Two-person pensioner - Men's outerwear, 195: RPI:Weights (parts per 1000) Two-person pensioner - Women's outerwear, 196: RPI:Weights (parts per 1000) Two-person pensioner - Children's outerwear, 197: RPI:Weights (parts per 1000) Two-person pensioner - Other clothing, 198: RPI:Weights (parts per 1000) Two-person pensioner - Footwear, 199: RPI:Weights (parts per 1000) Two-person pensioner - Personal articles, 200: RPI:Weights (parts per 1000) Two-person pensioner - Chemists goods, 201: RPI:Weights (parts per 1000) Two-person pensioner - Personal services, 202: RPI:Percentage change over 12 months - Biscuits and cakes, 203: RPI:Percentage change over 12 months - Beef, 204: RPI:Percentage change over 12 months - Lamb, 205: RPI:Percentage change over 12 months - home-killed lamb, 206: RPI:Percentage change over 12 months - Pork, 207: RPI:Percentage change over 12 months - Bacon, 208: RPI:Percentage change over 12 months - Poultry, 209: RPI:Percentage change over 12 months - Other meat, 210: RPI:Percentage change over 12 months - Fish, 211: RPI:Percentage change over 12 months - fresh fish, 212: RPI:Percentage change over 12 months - Butter, 213: RPI:Percentage change over 12 months - Oils and fats, 214: RPI:Percentage change over 12 months - Cheese, 215: RPI:Percentage change over 12 months - Eggs, 216: RPI:Weights (parts per 1000) Two-person pensioner - Purchase of motor vehicles, 217: RPI:Weights (parts per 1000) Two-person pensioner - Maintenance of motor vehicle, 218: RPI:Weights (parts per 1000) Two-person pensioner - Petrol and oil, 219: RPI:Weights (parts per 1000) Two-person pensioner - Vehicles tax and insurance, 220: RPI:Weights (parts per 1000) Two-person pensioner - Rail fares, 221: RPI:Weights (parts per 1000) Two-person pensioner - Bus and coach fares, 222: RPI:Weights (parts per 1000) Two-person pensioner - Other travel costs, 223: RPI:Weights (parts per 1000) Two-person pensioner - Audio-visual equipment, 224: RPI:Weights (parts per 1000) Two-person pensioner - Records and tapes, 225: RPI:Weights (parts per 1000) Two-person pensioner - Toys, photographic & sports, 226: RPI:Weights (parts per 1000) Two-person pensioner - Books and newspapers, 227: RPI:Weights (parts per 1000) Two-person pensioner - Gardening products, 228: RPI:Weights (parts per 1000) Two-person pensioner - Television licences and rent, 229: RPI:Weights (parts per 1000) Two-person pensioner - Entertainment & other recrea, 230: RPI:Weights (parts per 1000) Two-person pensioner - Food, 231: RPI:Weights (parts per 1000) Two-person pensioner - Catering, 232: RPI:Weights (parts per 1000) Two-person pensioner - Alcoholic drink, 233: RPI:Weights (parts per 1000) Two-person pensioner - Tobacco, 234: RPI:Weights (parts per 1000) Two-person pensioner - Fuel and light, 235: RPI:Weights (parts per 1000) Two-person pensioner - Household goods, 236: RPI:Weights (parts per 1000) Two-person pensioner - Household services, 237: RPI:Weights (parts per 1000) Two-person pensioner - Clothing and footwear, 238: RPI:Weights (parts per 1000) Two-person pensioner - Personal goods and services, 239: RPI:Weights (parts per 1000) Two-person pensioner - Motoring expenditure, 240: RPI:Weights (parts per 1000) Two-person pensioner - Fares and other travel costs, 241: RPI:Weights (parts per 1000) Two-person pensioner - Leisure goods, 242: RPI:Weights (parts per 1000) Two-person pensioner - Leisure services, 243: RPI: Percentage change over 12 months - Foreign holidays, 244: Retail Prices Index: Long run series: 1800 to 2024: Jan 1974=100, 245: RPI: Percentage change over 1 month - Food, 246: RPI All Items Excl Mortgage Interest (RPIX): Percentage change over 12 months, 247: Internal purchasing power of the pound (based on RPI): 1998=100, 248: Retail Prices Index: Long run series: annual percentage change, 249: RPI:Seasonally adjusted all items exc. MIPs and indirect taxes (SARPIY): Indices, 250: RPI: SA all items exc. MIPs and indirect taxes (SARPIY): % change over 12 months, 251: RPI: SA all items exc. MIPs and indirect taxes (SARPIY): % change over 1 month, 252: RPI All Items Index: Jan 1987=100, 253: RPI: All items exc. seasonal food (Jan 1987=100), 254: RPI: All items exc. food (Jan 1987=100), 255: RPI: All items exc. housing (Jan 1987=100), 256: RPI: Total food (Jan 1987=100), 257: RPI: Non-seasonal food (Jan 1987=100), 258: RPI: Catering (Jan 1987=100), 259: RPI: Alcoholic drink (Jan 1987=100), 260: RPI: Cigarettes & tobacco (Jan 1987=100), 261: RPI: Housing (Jan 1987=100), 262: RPI: Fuel & light (Jan 1987=100), 263: RPI: Household goods (Jan 1987=100), 264: RPI: Household services (Jan 1987=100), 265: RPI: Clothing & footwear (Jan 1987=100), 266: RPI: Motoring expenditure (Jan 1987=100), 267: RPI: Leisure goods (Jan 1987=100), 268: RPI: Leisure services (Jan 1987=100), 269: RPI: Seasonal food (Jan 1987=100), 270: RPI: Personal goods & services (Jan 1987=100), 271: RPI: Fares & other travel costs (Jan 1987=100), 272: RPI: Food & catering (Jan 1987=100), 273: RPI: Alcohol & tobacco (Jan 1987=100), 274: RPI: Housing & household expenditure (Jan 1987=100), 275: RPI: Personal expenditure (Jan 1987=100), 276: RPI: Travel & leisure (Jan 1987=100), 277: RPI: Consumer durables (Jan 1987=100), 278: RPI All Items Index Excl Mortgage Interest (RPIX): Jan 1987=100, 279: RPI: Leisure services: foreign holidays (Jan 1993=100), 280: RPI: Leisure services: UK Holidays (Jan 1994=100), 281: RPI: All Goods (Jan 1987=100), 282: RPI: All Services (Jan 1987=100), 283: RPI: Utilities (Jan 1987=100), 284: RPI: Shop Services (Jan 1987=100), 285: RPI: Non-Shop Services (Jan 1987=100), 286: RPI: Other Goods (Jan 1987=100), 287: RPI : Petrol and Oil (including fuel oil) (Jan 1987=100), 288: RPI: all items exc. mortgage interest payments and depreciation (Jan 1987=100), 289: RPI: housing: depreciation(Jan 1995=100), 290: CPI WEIGHTS 00 : HICP (Overall index), 291: CPI WEIGHTS 01 : FOOD AND NON-ALCOHOLIC BEVERAGES, 292: CPI WEIGHTS 02 : ALCOHOLIC DRINKS, TOBACCO AND NARCOTICS, 293: CPI WEIGHTS 03 : CLOTHING AND FOOTWEAR, 294: CPI WEIGHTS 04 : HOUSING, WATER AND FUELS, 295: CPI WEIGHTS 05 : FURN, HH EQUIPMENT AND REPAIR OF THE HOUSE, 296: CPI WEIGHTS 06 : HEALTH, 297: CPI WEIGHTS 07 : TRANSPORT, 298: CPI WEIGHTS 08 : COMMUNICATION, 299: CPI WEIGHTS 09 : RECREATION & CULTURE, 300: CPI WEIGHTS 10 : EDUCATION, 301: CPI WEIGHTS 11 : HOTELS, CAFES AND RESTAURANTS, 302: CPI WEIGHTS 12 : MISCELLANEOUS GOODS AND SERVICES, 303: CPI WEIGHTS 01.1 : FOOD, 304: CPI WEIGHTS 01.2 : NON-ALCOHOLIC BEVERAGES, 305: CPI WEIGHTS 02.1 : ALCOHOLIC BEVERAGES, 306: CPI WEIGHTS 03.1 : CLOTHING, 307: CPI WEIGHTS 03.2 : FOOTWEAR INCLUDING REPAIRS, 308: CPI WEIGHTS 04.1 : ACTUAL RENTS FOR HOUSING, 309: CPI WEIGHTS 04.3 : REGULAR MAINTENANCE AND REPAIR OF THE DWELLING, 310: CPI WEIGHTS 04.4 : Water sup

,Title,CPI wts: Non-energy industrial goods GOODS,CPI wts: Durables GOODS,CPI wts: Semi-durables GOODS,CPI wts: Non-durables GOODS,CPI wts: Non-seasonal food GOODS,"CPI wts: Food, alcoholic beverages & tobacco GOODS",CPI wts: Processed food & non-alcoholic beverages GOODS,CPI wts: Unprocessed food GOODS,CPI wts: Seasonal food GOODS,...,CPI: % points change over previous month (12 month rate): Furniture & hhold good,CPI: % points change over previous month (12 month rate): Health,CPI: % points change over previous month (12 month rate): Transport,CPI: % points change over previous month (12 month rate): Communication,CPI: % points change over previous month (12 month rate): Recreation & culture,CPI: % points change over previous month (12 month rate): Education,CPI: % points change over previous month (12 month rate): Restaurants & hotels,CPI: % points change over previous month (12 month rate): Misc goods & services,Internal purchasing power of the pound (based on RPI): 2000 = 100,"RPI: Ave price - Salmon fillets, per Kg"
0,CDID,A9ER,A9ES,A9ET,A9EU,A9EV,A9EW,A9EX,A9EY,A9EZ,...,WUNQ,WUNZ,WUOA,WUOO,WUOP,WUOU,WUOV,WUOW,ZMHO,ZPTX
1,PreUnit,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Unit,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,Parts per 1000,...,%,%,%,%,%,%,%,%,Pence,Pence
3,Release Date,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,...,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026,17-06-2026
4,Next release,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,...,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026,22 July 2026

In [18]:
inflation_df.columns[inflation_df.columns.str.contains("CPIH INDEX 00: ALL ITEMS", regex=False)]

Index(['CPIH INDEX 00: ALL ITEMS 2015=100'], dtype='str')

In [19]:
inflation = inflation_df [
    [
        "Title",
        "CPIH INDEX 00: ALL ITEMS 2015=100"
    ]
].copy()

inflation.head()

          Title CPIH INDEX 00: ALL ITEMS 2015=100
0          CDID                              L522
1       PreUnit                               NaN
2          Unit            Index, base year = 100
3  Release Date                        17-06-2026
4  Next release                      22 July 2026

In [20]:
inflation = inflation.rename(columns={
    "Title": "time_period",
    "CPIH INDEX 00: ALL ITEMS 2015=100": "cpih_index"
})

In [21]:
inflation = inflation[
    inflation["time_period"].str.match(r"^\d{4} [A-Z]{3}$", na=False)
].copy()

In [22]:
inflation["time_period"] = pd.to_datetime(
    inflation["time_period"],
    format="%Y %b"
)

inflation["cpih_index"] = pd.to_numeric(
    inflation["cpih_index"],
    errors="coerce"
)

inflation.head()

    time_period  cpih_index
544  1947-06-01         NaN
545  1947-07-01         NaN
546  1947-08-01         NaN
547  1947-09-01         NaN
548  1947-10-01         NaN

In [23]:
inflation.tail()

     time_period  cpih_index
1487  2026-01-01       139.4
1488  2026-02-01       140.0
1489  2026-03-01       140.8
1490  2026-04-01       141.8
1491  2026-05-01       142.1

In [24]:
inflation.to_csv(
    "../data/processed/inflation_clean.csv",
    index=False
)

In [25]:
pd.read_csv("../data/processed/inflation_clean.csv").head()

  time_period  cpih_index
0  1947-06-01         NaN
1  1947-07-01         NaN
2  1947-08-01         NaN
3  1947-09-01         NaN
4  1947-10-01         NaN